name: Kernel A15 6.6 (Single Build)

on:
  workflow_call:
    inputs:
      ksu_variant:
        required: true
        type: string

      require_susfs:
        required: true
        type: boolean

jobs:
  build-a15-6-6:
    name: Android 15 â€¢ Kernel 6.6.${{ matrix.sub_level }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        sub_level: ["98", "102"]
    with:
      android_version: android15
      kernel_version: "6.6"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: "2025-10"
      ksu_variant: ${{ inputs.ksu_variant }}
      require_susfs: ${{ inputs.require_susfs }}
