name: Kernel A15 6.6 (Single Build)

on:
  workflow_call:
    inputs:
      kernel_sublevel:
        type: string
        required: false
        default: "102"

      os_patch_level:
        type: string
        required: false
        default: "2025-10"

      ksu_variant:
        type: string
        required: true

      require_susfs:
        type: boolean
        required: true

jobs:
  build-a15-6-6:
    name: Android 15 â€¢ Kernel 6.6.${{ inputs.kernel_sublevel }}
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: android15
      kernel_version: "6.6"
      sub_level: ${{ inputs.kernel_sublevel }}
      os_patch_level: ${{ inputs.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant }}
      require_susfs: ${{ inputs.require_susfs }}
